#!/usr/bin/env python3
"""Write the repo's agent charter (AGENTS.md) and link CLAUDE.md to it.

Part of harness-setup's RECORD step. AGENTS.md is what makes the harness
self-describing to the next agent (or human) who opens the repo: it states the
loop, the layer map, the shelf-check rungs, and how to run the gates — generated
from boundary.config.json so it reflects THIS repo. CLAUDE.md is a symlink to it
so Claude Code and AGENTS.md-convention tools read one source of truth.

The harness-owned content lives between managed markers and is regenerated on
each run; anything outside the markers (e.g. the "Repo conventions & learnings"
section — the durable home for the outer-loop ratchet's output) is never touched.

Usage:
    python agents_init.py --repo .            # create/refresh AGENTS.md + CLAUDE.md
    python agents_init.py --repo . --force    # overwrite an existing CLAUDE.md file
"""
from __future__ import annotations

import argparse
import errno
import json
import os
from pathlib import Path

START = "<!-- harness:managed:start — regenerated by harness-setup; edit outside this block -->"
END = "<!-- harness:managed:end -->"


def load_config(repo: Path) -> dict:
    p = repo / "boundary.config.json"
    if not p.exists():
        return {}
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}


def managed_block(cfg: dict) -> str:
    layers = cfg.get("layers", {})
    layer_rows = "\n".join(
        f"| {name} | {', '.join(globs) if isinstance(globs, list) else globs} |"
        for name, globs in layers.items()
    ) or "| (run harness-setup to populate) | |"
    verify = cfg.get("verify", [])
    verify_rows = "\n".join(
        f"- `{c.get('cmd')}` — {c.get('name')}"
        + ("" if c.get("must_pass", True) else " (report-only)")
        for c in verify
    ) or "- (none configured yet)"
    feature_roots = ", ".join(cfg.get("feature_roots", [])) or "(none)"

    return f"""{START}

# Working in this repo (the boundary harness)

This repo is built with a **federation of skills** whose goal is that the
marginal cost of feature N+1 slopes *down*. You do that by reusing the substrate
and keeping boundaries in their right place — not by moving fast and duplicating.
Run the loop; don't freelance.

**Foundations:** [`.harness/CONSTITUTION.md`](./.harness/CONSTITUTION.md) (the
principles) and [`.harness/HARNESS.md`](./.harness/HARNESS.md) (the mechanics) —
installed by harness-setup; read them once to know why the loop is shaped this way.

## The loop (per feature)

1. **Plan** — scaffold and fill `PLAN.md` (`feature-workflow` → `plan_new.py`),
   then pass the gate (`plan_check.py`). Decompose boundaries, list the bill of
   materials, and classify every item (next section). The gate blocks building
   until the plan is complete.
2. **Build** — compose REUSE/EXTEND first; build the rest via `boundary-discipline`
   (IMPLEMENT mode). Place each unit in its layer (table below). Keep illegal
   states unrepresentable and effects at the rim (pure core / imperative shell).
3. **Verify** — run the gate (`verify.py`); see checks below. The pure core is
   mockless-testable anywhere; the shell needs the real toolchain.
4. **Record** — write shelf deposits into `PLAN.md`; feed recurring friction to
   the ratchet (see "Repo conventions & learnings" below).

## Shelf-check rungs (classify every bill-of-materials item)

- **REUSE** — it exists internally and fits; take it as-is.
- **EXTEND** — it exists internally; generalize it (non-breakingly).
- **VENDOR** — an external library already solves this; reuse its capability.
  Outranks BUILD. Check `library-knowledge` (`lib_lookup.py --search "<capability>"`)
  before hand-rolling. A library is a new external trust + maintenance boundary,
  so vendor a real capability that replaces code you'd own, not something trivial.
- **BUILD** — nothing solves it; write it. Last resort, not first.

## Library knowledge (the ecosystem trust boundary)

Never emit a fast-moving library's current API from memory — it is stale the
moment a version ships. Consult `lib_lookup.py <name>` for confirmed facts; on a
miss or STALE verdict, confirm against official docs and record with
`lib_refresh.py --set`. Store: `lib-knowledge.jsonl`.

## Layer → directory map

| layer | paths |
|---|---|
{layer_rows}

Feature roots: {feature_roots}

## Verify gate

{verify_rows}

{END}"""


def learnings_section() -> str:
    return """## Repo conventions & learnings

_Outside the managed block — harness-setup never edits below. This is the home
for the outer-loop ratchet: when a friction recurs three times, capture the
durable fix here (a convention, a lint rule, a scan-pattern note, or a pointer
to a new reference/skill) so it stops recurring._

- (none yet)
"""


def write_agents(repo: Path) -> str:
    cfg = load_config(repo)
    block = managed_block(cfg)
    p = repo / "AGENTS.md"
    if p.exists():
        text = p.read_text(encoding="utf-8")
        if START in text and END in text:
            pre, rest = text.split(START, 1)
            _, post = rest.split(END, 1)
            p.write_text(pre + block + post, encoding="utf-8")
            return "refreshed managed block (preserved your edits)"
        # exists but unmanaged: prepend the block, keep their content
        p.write_text(block + "\n\n" + text, encoding="utf-8")
        return "prepended managed block to existing AGENTS.md"
    p.write_text(block + "\n\n" + learnings_section(), encoding="utf-8")
    return "created AGENTS.md"


def link_claude(repo: Path, force: bool) -> str:
    link = repo / "CLAUDE.md"
    if link.is_symlink():
        if os.readlink(link) == "AGENTS.md":
            return "CLAUDE.md -> AGENTS.md (already linked)"
        if not force:
            return f"CLAUDE.md is a symlink to {os.readlink(link)} — leaving it (use --force to relink)"
        link.unlink()
    elif link.exists():
        if not force:
            return "CLAUDE.md exists as a real file — leaving it (use --force to replace with a symlink)"
        link.unlink()
    try:
        os.symlink("AGENTS.md", link)  # relative link, repo-portable — the preferred form
        return "linked CLAUDE.md -> AGENTS.md (symlink)"
    except OSError as e:
        # Some filesystems (certain sandboxes, some network mounts) don't implement
        # symlinks. Degrade to a pointer file so tooling still finds the guidance;
        # on a normal repo filesystem this branch never runs.
        if e.errno in (errno.ENOSYS, errno.EPERM, errno.EACCES):
            link.write_text(
                "See [AGENTS.md](./AGENTS.md) — the single source of truth for "
                "agent guidance in this repo.\n\n"
                "<!-- Preferred form is a symlink: ln -sf AGENTS.md CLAUDE.md . "
                "This filesystem does not support symlinks, so this is a pointer file. -->\n",
                encoding="utf-8",
            )
            return f"filesystem has no symlink support (errno {e.errno}); wrote CLAUDE.md as a pointer to AGENTS.md"
        raise


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Write AGENTS.md + link CLAUDE.md (harness RECORD step).")
    ap.add_argument("--repo", default=".")
    ap.add_argument("--force", action="store_true", help="Replace an existing CLAUDE.md.")
    args = ap.parse_args(argv)
    repo = Path(args.repo).resolve()
    print(write_agents(repo))
    print(link_claude(repo, args.force))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
